on:
  push:
    branches:
      - minified

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: minified
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOSATUR_E21BE }}
          projectId: tosatur-e21be
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          channelID: live